# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/configure/yaml/

snapshot: lts-24.28

packages:
- .

extra-deps:
- Agda-2.8.0

flags: {}

extra-package-dbs: []

ghc-options:
  "$locals": -Wall -fno-warn-unused-matches -fno-warn-unused-imports -fno-warn-unused-local-binds -fno-warn-incomplete-patterns -fno-warn-name-shadowing
